services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    networks:
      - clinical-trials-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5050
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - clinical-trials-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - clinical-trials-network

volumes:
  postgres_data:

networks:
  clinical-trials-network:
    driver: bridge